apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-deployment
  labels:
    app: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: registry.cn-qingdao.aliyuncs.com/lxjian01/nginx:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: harbor-secret1
