version: "1.0.0"
env: "dev"
yamlDir: "/opt/code/kubernetes-yamls"
poolNum: 100
httpd:
  host: "0.0.0.0"
  port: 8018
log:
  dir: "/data/cmdb/logs"
  name: "kubernetes-go-demo.log"
  format: ""
  retainDay: 3
  Level: "INFO"
mysql:
  host: "192.168.219.128"
  port: 3306
  dbName: "kubernetes-demo"
  user: "root"
  password: "123456"
  maxConn: 30
  maxOpen: 30
redis:
  host: "192.168.219.128"
  port: 6379
  maxIdle: 3
  maxActive: 5
  idleTimeout: 60
machinery:
  broker: 192.168.219.128:6379
  backend: 192.168.219.128:6379
  defaultQueue: "machinery_tasks"